[package]
name = "janadinite-vm"
version = "0.1.0"
edition = "2024"
authors = ["safiworks safiworks0@gmail.com"]
license = "MIT"
description = "A JIT powered JVM and JVM library wrote in rust"

[workspace]
members = ["janadinite-parse", "macros"]

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
hybrid-rc = "0.6.0"
janadinite-parse = { path = "janadinite-parse" }
rustc-hash = { version = "2.1.3", default-features = false }
