mod constant_pool;
mod raw;

use crate::io;
use crate::io::invalid_data;

pub use constant_pool::*;
pub use raw::*;

extern crate alloc;
use alloc::boxed::Box;
use alloc::sync::Arc;

use crate::io::{ClassByteReader, ClassDecode, ClassReader};

bitflags::bitflags! {
    /**
     The value of the access_flags item is a mask of flags used to denote access permissions to and properties of this class or interface. The interpretation of each flag, when set, is specified in Table 4.1-A.
     Table 4.1-A. Class access and property modifiers
   */
    #[derive(Debug, Clone, Copy)]
    pub struct JVMAccessFlag: u16 {
        /// Declared public; may be accessed from outside its package.
         const ACC_PUBLIC = 0x0001;
        /// Declared private; accessible only within the defining class.
         const ACC_PRIVATE = 0x0002;
        /// Declared protected; may be accessed within subclasses.
         const ACC_PROTECTED = 0x0004;
        /// Declared static.
         const ACC_STATIC = 0x0008;
        /// Declared final; must not be overridden (§5.4.5).
         const ACC_FINAL = 0x0010;
        /// Declared synchronized; invocation is wrapped by a monitor use.
         const ACC_SYNCHRONIZED = 0x0020;
        /// A bridge method, generated by the compiler.
         const ACC_BRIDGE = 0x0040;
        /// Declared with variable number of arguments.
         const ACC_VARARGS = 0x0080;
        /// Declared native; implemented in a language other than Java.
         const ACC_NATIVE = 0x0100;
        /// Declared abstract; no implementation is provided.
         const ACC_ABSTRACT = 0x0400;
        /// Declared strictfp; floating-point mode is FP-strict.
         const ACC_STRICT = 0x0800;
        /// Declared synthetic; not present in the source code.
         const ACC_SYNTHETIC = 0x1000;
    }
}

/// Describes all (implemented) JVM instructions.
#[derive(macros::OpcodeDecode, Debug, Clone, Copy, PartialEq, Eq)]
#[decode(wide_prefix = 0xc4, fallback = custom_decode)]
#[repr(u8)]
pub enum OpCode {
    /// Push long constant 0
    Lconst0 = 0x9,
    /// Push long constant 1
    Lconst1 = 0xa,
    /// Push float 0
    Fconst0 = 0xb,
    /// Push float 1
    Fconst1 = 0xc,
    /// Push float 2
    Fconst2 = 0xd,
    /// Push double 0
    Dconst0 = 0xe,
    /// Push double 1
    Dconst1 = 0xf,
    /// Push item from run-time constant pool
    /// The index is an unsigned byte that must be a valid index into the run-time constant pool of the current class (§2.6). The run-time constant pool entry at index either must be a run-time constant of type int or float, or a reference to a string literal, or a symbolic reference to a class, method type, or method handle (§5.1).
    ///
    /// If the run-time constant pool entry is a run-time constant of type int or float, the numeric value of that run-time constant is pushed onto the operand stack as an int or float, respectively.
    ///
    /// Otherwise, if the run-time constant pool entry is a reference to an instance of class String representing a string literal (§5.1), then a reference to that instance, value, is pushed onto the operand stack.
    ///
    /// Otherwise, if the run-time constant pool entry is a symbolic reference to a class (§5.1), then the named class is resolved (§5.4.3.1) and a reference to the Class object representing that class, value, is pushed onto the operand stack.
    ///
    /// Otherwise, the run-time constant pool entry must be a symbolic reference to a method type or a method handle (§5.1). The method type or method handle is resolved (§5.4.3.5) and a reference to the resulting instance of java.lang.invoke.MethodType or java.lang.invoke.MethodHandle, value, is pushed onto the operand stack
    Ldc(u8) = 0x12,
    /// Wide version of [`Self::Ldc`].
    LdcW(u16) = 0x13,
    /// Push long or double from run-time constant pool (wide index)
    Ldc2W(u16) = 0x14,
    /// Load int from local variable
    ///
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6). The local variable at index must contain an int. The value of the local variable at index is pushed onto the operand stack.
    #[decode(short(base = 0x1a, count = 4))] /* TODO: iload<n> */
    Iload(u8) = 0x15,
    /// Load long from local variable.
    ///
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6). The local variable at index must contain a long. The value of the local variable at index is pushed onto the operand stack.
    #[decode(short(base = 0x1e, count = 4))]
    Lload(u8) = 0x16,
    /// Load float from local variable.
    ///
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6). The local variable at index must contain a float. The value of the local variable at index is pushed onto the operand stack.
    #[decode(short(base = 0x22, count = 4))]
    Fload(u8) = 0x17,
    /// Load double from local variable.
    ///
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6). The local variable at index must contain a double. The value of the local variable at index is pushed onto the operand stack.
    #[decode(short(base = 0x26, count = 4))]
    Dload(u8) = 0x18,
    /// Load reference from local variable.
    #[decode(short(base = 0x2a, count = 4))]
    Aload(u8) = 0x19,
    /// Store int into local variable
    ///
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6). The value on the top of the operand stack must be of type int. It is popped from the operand stack, and the value of the local variable at index is set to value.
    #[decode(short(base = 0x3b, count = 4))]
    IStore(u8) = 0x36,
    /// Store long into local variable.
    #[decode(short(base = 0x3f, count = 4))]
    LStore(u8) = 0x37,
    /// Store float into local variable
    #[decode(short(base = 0x43, count = 4))]
    FStore(u8) = 0x38,
    /// Store double into local variable.
    #[decode(short(base = 0x47, count = 4))]
    DStore(u8) = 0x39,
    /// Store reference into local variable.
    #[decode(short(base = 0x4b, count = 4))]
    AStore(u8) = 0x3a,
    /// Load int from array
    ///
    /// The arrayref must be of type reference and must refer to an array whose components are of type int. The index must be of type int. Both arrayref and index are popped from the operand stack. The int value in the component of the array at index is retrieved and pushed onto the operand stack.
    IALoad = 0x2e,
    /// Load long from array
    LALoad = 0x2f,
    /// Store into long array
    LAStore = 0x50,

    /// Store into int array
    ///
    /// The arrayref must be of type reference and must refer to an array whose components are of type int. Both index and value must be of type int. The arrayref, index, and value are popped from the operand stack. The int value is stored as the component of the array indexed by index.
    IAStore = 0x4f,

    /// Load float from array
    FALoad = 0x30,
    /// Store into float array
    FAStore = 0x51,

    /// Load byte or boolean from array
    ///
    ///  The arrayref must be of type reference and must refer to an array whose components are of type byte or of type boolean. The index must be of type int. Both arrayref and index are popped from the operand stack. The byte value in the component of the array at index is retrieved, sign-extended to an int value, and pushed onto the top of the operand stack.
    BALoad = 0x33,
    /// Store into byte or boolean array
    ///
    ///  The arrayref must be of type reference and must refer to an array whose components are of type byte or of type boolean. The index and the value must both be of type int. The arrayref, index, and value are popped from the operand stack. The int value is truncated to a byte and stored as the component of the array indexed by index.
    BAStore = 0x54,
    /// Load char from array
    ///
    ///  The arrayref must be of type reference and must refer to an array whose components are of type char. The index must be of type int. Both arrayref and index are popped from the operand stack. The component of the array at index is retrieved and zero-extended to an int value. That value is pushed onto the operand stack.
    CALoad = 0x34,
    /// Store into char array
    ///
    ///  The arrayref must be of type reference and must refer to an array whose components are of type char. The index and the value must both be of type int. The arrayref, index, and value are popped from the operand stack. The int value is truncated to a char and stored as the component of the array indexed by index.
    CAStore = 0x55,
    /// Load double from array
    DALoad = 0x31,
    /// Store into double array
    DAStore = 0x52,
    /// Load short from array
    SALoad = 0x35,
    /// Store into short array
    SAStore = 0x56,
    /// Load reference from array
    AALoad = 0x32,
    /// Store into reference array
    AAStore = 0x53,

    /// Push Byte. The immediate byte is sign-extended to an int value. That value is pushed onto the operand stack.
    #[decode(skip)]
    Bipush(i8) = 0x10,
    /// Duplicate the top operand stack value.
    Dup = 0x59,
    /// Duplicate the top operand stack value and insert two values down.
    DupX1 = 0x5a,
    /// Duplicate the top operand stack value and insert two or three values down
    DupX2 = 0x5b,
    /// Duplicate the top one or two operand stack values
    Dup2 = 0x5c,
    /// Duplicate the top one or two operand stack values and insert two or three values down.
    Dup2X1 = 0x5d,
    /// Duplicate the top one or two operand stack values and insert two, three, or four values down.
    Dup2X2 = 0x5e,
    /// Increment local variable by constant.
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6).
    ///
    /// The const is an immediate signed byte. The local variable at index must contain an int. The value const is first sign-extended to an int, and then the local variable at index is incremented by that amount.
    Iinc(u8, i8) = 0x84,
    /// Multiply int.
    ///
    ///  Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 * value2. The result is pushed onto the operand stack.
    ///
    /// The result is the 32 low-order bits of the true mathematical result in a sufficiently wide two's-complement format, represented as a value of type int. If overflow occurs, then the sign of the result may not be the same as the sign of the mathematical multiplication of the two values.
    ///
    /// Despite the fact that overflow may occur, execution of an imul instruction never throws a run-time exception
    Imul = 0x68,
    /// Multiply long.
    ///
    /// Both value1 and value2 must be of type long. The values are popped from the operand stack. The long result is value1 * value2. The result is pushed onto the operand stack.
    ///
    /// The result is the 64 low-order bits of the true mathematical result in a sufficiently wide two's-complement format, represented as a value of type long. If overflow occurs, the sign of the result may not be the same as the sign of the mathematical multiplication of the two values.
    ///
    /// Despite the fact that overflow may occur, execution of an lmul instruction never throws a run-time exception.
    Lmul = 0x69,
    /// Multiply float.
    ///
    /// Both value1 and value2 must be of type float. The values are popped from the operand stack and multiplied according to IEEE 754 rules. The float result is pushed onto the operand stack.
    Fmul = 0x6a,
    /// Multiply double.
    ///
    /// Both value1 and value2 must be of type double. The values are popped from the operand stack and multiplied according to IEEE 754 rules. The double result is pushed onto the operand stack.
    Dmul = 0x6b,
    /// Divide int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 / value2. The result is pushed onto the operand stack.
    Idiv = 0x6c,
    /// Divide long.
    ///
    /// Both value1 and value2 must be of type long. The values are popped from the operand stack. The long result is value1 / value2. The result is pushed onto the operand stack.
    Ldiv = 0x6d,
    /// Divide float.
    ///
    /// Both value1 and value2 must be of type float. The values are popped from the operand stack and divided according to IEEE 754 rules. The float result is pushed onto the operand stack.
    Fdiv = 0x6e,
    /// Divide double.
    ///
    /// Both value1 and value2 must be of type double. The values are popped from the operand stack and divided according to IEEE 754 rules. The double result is pushed onto the operand stack.
    Ddiv = 0x6f,
    /// Subtract int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 - value2. The result is pushed onto the operand stack.
    Isub = 0x64,
    /// Subtract long.
    ///
    /// Both value1 and value2 must be of type long. The values are popped from the operand stack. The long result is value1 - value2. The result is pushed onto the operand stack.
    Lsub = 0x65,
    /// Subtract float.
    ///
    /// Both value1 and value2 must be of type float. The values are popped from the operand stack and subtracted according to IEEE 754 rules. The float result is pushed onto the operand stack.
    Fsub = 0x66,
    /// Subtract double.
    ///
    /// Both value1 and value2 must be of type double. The values are popped from the operand stack and subtracted according to IEEE 754 rules. The double result is pushed onto the operand stack.
    Dsub = 0x67,
    /// Add int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 + value2. The result is pushed onto the operand stack.
    Iadd = 0x60,
    /// Add long.
    ///
    /// Both value1 and value2 must be of type long. The values are popped from the operand stack. The long result is value1 + value2. The result is pushed onto the operand stack.
    Ladd = 0x61,
    /// Add float.
    ///
    /// Both value1 and value2 must be of type float. The values are popped from the operand stack and added according to IEEE 754 rules. The float result is pushed onto the operand stack.
    Fadd = 0x62,
    /// Add double.
    ///
    /// Both value1 and value2 must be of type double. The values are popped from the operand stack and added according to IEEE 754 rules. The double result is pushed onto the operand stack.
    Dadd = 0x63,
    /// Remainder int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 - (value1 / value2) * value2, matching the sign of value1. The result is pushed onto the operand stack.
    Irem = 0x70,
    /// Remainder long.
    ///
    /// Both value1 and value2 must be of type long. The values are popped from the operand stack. The long result is value1 - (value1 / value2) * value2, matching the sign of value1. The result is pushed onto the operand stack.
    Lrem = 0x71,
    /// Remainder float.
    ///
    /// Both value1 and value2 must be of type float. The values are popped from the operand stack and the IEEE 754 float remainder of value1 by value2 is computed and pushed onto the operand stack.
    Frem = 0x72,
    /// Remainder double.
    ///
    /// Both value1 and value2 must be of type double. The values are popped from the operand stack and the IEEE 754 double remainder of value1 by value2 is computed and pushed onto the operand stack.
    Drem = 0x73,
    /// Negate int.
    ///
    /// The value must be of type int. It is popped from the operand stack. The int result is -value. The result is pushed onto the operand stack.
    Ineg = 0x74,
    /// Negate long.
    ///
    /// The value must be of type long. It is popped from the operand stack. The long result is -value. The result is pushed onto the operand stack.
    Lneg = 0x75,
    /// Negate float.
    ///
    /// The value must be of type float. It is popped from the operand stack. The float result is -value, computed per IEEE 754 negation rules. The result is pushed onto the operand stack.
    Fneg = 0x76,
    /// Negate double.
    ///
    /// The value must be of type double. It is popped from the operand stack. The double result is -value, computed per IEEE 754 negation rules. The result is pushed onto the operand stack.
    Dneg = 0x77,
    /// Shift int left.
    ///
    /// value1 must be of type int and value2 must be of type int. Both are popped from the operand stack. An int result is calculated by shifting value1 left by the number of bit positions given by the low 5 bits of value2. The result is pushed onto the operand stack.
    Ishl = 0x78,
    /// Shift long left.
    ///
    /// value1 must be of type long and value2 must be of type int. Both are popped from the operand stack. A long result is calculated by shifting value1 left by the number of bit positions given by the low 6 bits of value2. The result is pushed onto the operand stack.
    Lshl = 0x79,
    /// Arithmetic shift int right.
    ///
    /// value1 must be of type int and value2 must be of type int. Both are popped from the operand stack. An int result is calculated by shifting value1 right, sign-extending, by the number of bit positions given by the low 5 bits of value2. The result is pushed onto the operand stack.
    Ishr = 0x7a,
    /// Arithmetic shift long right.
    ///
    /// value1 must be of type long and value2 must be of type int. Both are popped from the operand stack. A long result is calculated by shifting value1 right, sign-extending, by the number of bit positions given by the low 6 bits of value2. The result is pushed onto the operand stack.
    Lshr = 0x7b,
    /// Logical shift int right.
    ///
    /// value1 must be of type int and value2 must be of type int. Both are popped from the operand stack. An int result is calculated by shifting value1 right, filling with zeros, by the number of bit positions given by the low 5 bits of value2. The result is pushed onto the operand stack.
    Iushr = 0x7c,
    /// Logical shift long right.
    ///
    /// value1 must be of type long and value2 must be of type int. Both are popped from the operand stack. A long result is calculated by shifting value1 right, filling with zeros, by the number of bit positions given by the low 6 bits of value2. The result is pushed onto the operand stack.
    Lushr = 0x7d,
    /// Boolean AND int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is the bitwise AND of value1 and value2. The result is pushed onto the operand stack.
    Iand = 0x7e,
    /// Boolean AND long.
    ///
    /// Both value1 and value2 must be of type long. The values are popped from the operand stack. The long result is the bitwise AND of value1 and value2. The result is pushed onto the operand stack.
    Land = 0x7f,
    /// Boolean OR int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is the bitwise OR of value1 and value2. The result is pushed onto the operand stack.
    Ior = 0x80,
    /// Boolean OR long.
    ///
    /// Both value1 and value2 must be of type long. The values are popped from the operand stack. The long result is the bitwise OR of value1 and value2. The result is pushed onto the operand stack.
    Lor = 0x81,
    /// Boolean XOR int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is the bitwise XOR of value1 and value2. The result is pushed onto the operand stack.
    Ixor = 0x82,
    /// Boolean XOR long.
    ///
    /// Both value1 and value2 must be of type long. The values are popped from the operand stack. The long result is the bitwise XOR of value1 and value2. The result is pushed onto the operand stack.
    Lxor = 0x83,
    /// Convert int to long
    ///
    ///  The value on the top of the operand stack must be of type int. It is popped from the operand stack and sign-extended to a long result. That result is pushed onto the operand stack.
    I2l = 0x85,
    /// Convert int to float
    I2f = 0x86,
    /// Convert int to double
    I2d = 0x87,
    /// Branch always/
    Goto(i16) = 0xa7,
    /// Compare float
    ///
    ///
    /// Both value1 and value2 must be of type float. The values are popped from the operand stack and undergo value set conversion (§2.8.3), resulting in value1' and value2'. A floating-point comparison is performed:
    ///
    /// If value1' is greater than value2', the int value 1 is pushed onto the operand stack.
    ///
    ///
    /// Otherwise, if value1' is equal to value2', the int value 0 is pushed onto the operand stack.
    ///
    ///
    /// Otherwise, if value1' is less than value2', the int value -1 is pushed onto the operand stack.
    ///
    ///  Otherwise, at least one of value1' or value2' is NaN. The fcmpg instruction pushes the int value 1 onto the operand stack and the fcmpl instruction pushes the int value -1 onto the operand stack.
    Fcmpg = 0x96,
    /// Same a [`Self::Fcmpg`] but on NaN pushes -1.
    Fcmpl = 0x95,
    /// Compare double
    ///
    ///
    /// If value1' is greater than value2', the int value 1 is pushed onto the operand stack.
    ///
    /// Otherwise, if value1' is equal to value2', the int value 0 is pushed onto the operand stack.
    ///
    /// Otherwise, if value1' is less than value2', the int value -1 is pushed onto the operand stack.
    ///
    /// Otherwise, at least one of value1' or value2' is NaN. The dcmpg instruction pushes the int value 1 onto the operand stack and the dcmpl instruction pushes the int value -1 onto the operand stack.
    Dcmpg = 0x98,
    /// Same as [`Self::Dcmpg`] but on NaN pushes -1.
    Dcmpl = 0x97,
    /// Branch if int comparison succeeds.
    ///
    /// Both value1 and value2 must be of type int. They are both popped from the operand stack and compared. All comparisons are signed. The results of the comparison are as follows:
    ///
    /// if_icmpeq succeeds if and only if value1 = value2
    IfIcmpEq(i16) = 0x9f,
    /// Branch if int comparison fails.
    ///
    /// Both value1 and value2 must be of type int. They are both popped from the operand stack and compared. All comparisons are signed. The results of the comparison are as follows:
    ///
    /// if_icmpne succeeds if and only if value1 != value2
    IfIcmpNe(i16) = 0xa0,
    /// if_icmplt succeeds if and only if value1 < value2
    IfIcmpLt(i16) = 0xa1,
    /// if_icmpge succeeds if and only if value1 ≥ value2
    IfIcmpGe(i16) = 0xa2,
    /// if_icmpgt succeeds if and only if value1 > value2
    IfIcmpGt(i16) = 0xa3,
    /// if_icmple succeeds if and only if value1 ≤ value2
    IfIcmpLe(i16) = 0xa4,
    /// Compare long
    ///
    ///  Both value1 and value2 must be of type long. They are both popped from the operand stack, and a signed integer comparison is performed. If value1 is greater than value2, the int value 1 is pushed onto the operand stack. If value1 is equal to value2, the int value 0 is pushed onto the operand stack. If value1 is less than value2, the int value -1 is pushed onto the operand stack.
    Lcmp = 0x94,
    /// Branch if int comparison with zero succeeds.
    /// The value must be of type int. It is popped from the operand stack and compared against zero. All comparisons are signed. The results of the comparisons are as follows:
    /// - ifne succeeds if and only if value ≠ 0.
    IfNe(i16) = 0x9a,
    /// Branch if int comparison with zero fails.
    /// The value must be of type int. It is popped from the operand stack and compared against zero. All comparisons are signed. The results of the comparisons are as follows:
    /// - ifeq succeeds if and only if value = 0.
    IfEq(i16) = 0x99,
    /// Return int from method.
    ///
    ///  The current method must have return type boolean, byte, short, char, or int. The value must be of type int. If the current method is a synchronized method, the monitor entered or reentered on invocation of the method is updated and possibly exited as if by execution of a monitorexit instruction (§monitorexit) in the current thread. If no exception is thrown, value is popped from the operand stack of the current frame (§2.6) and pushed onto the operand stack of the frame of the invoker. Any other values on the operand stack of the current method are discarded.
    IReturn = 0xac,
    /// Return long from method.
    ///
    /// The current method must have return type long. The value on top of the operand stack must be of type long. It is popped from the operand stack of the current frame and pushed onto the operand stack of the frame of the invoker.
    LReturn = 0xad,
    /// Return float from method.
    ///
    /// The current method must have return type float. The value on top of the operand stack must be of type float. It is popped from the operand stack of the current frame and pushed onto the operand stack of the frame of the invoker.
    FReturn = 0xae,
    /// Return double from method.
    ///
    /// The current method must have return type double. The value on top of the operand stack must be of type double. It is popped from the operand stack of the current frame and pushed onto the operand stack of the frame of the invoker.
    DReturn = 0xaf,
    /// Return reference from method.
    ///
    /// The current method must have a reference return type. The value on top of the operand stack must be a reference. It is popped from the operand stack of the current frame and pushed onto the operand stack of the frame of the invoker.
    AReturn = 0xb0,
    /// Invoke instance method; dispatch based on class
    InvokeVirtual(u16) = 0xb6,
    /// Invoke instance method; special handling for superclass, private, and instance initialization method invocations
    InvokeSpecial(u16) = 0xb7,
    /// Invoke a class (static) method.
    InvokeStatic(u16) = 0xb8,
    /// Return void from method.
    Return = 0xb1,
    /// Get static field from class.
    /// The unsigned indexbyte1 and indexbyte2 are used to construct an index into the run-time constant pool of the current class (§2.6), where the value of the index is (indexbyte1 << 8) | indexbyte2. The run-time constant pool item at that index must be a symbolic reference to a field (§5.1), which gives the name and descriptor of the field as well as a symbolic reference to the class or interface in which the field is to be found. The referenced field is resolved (§5.4.3.2).
    ///
    /// On successful resolution of the field, the class or interface that declared the resolved field is initialized (§5.5) if that class or interface has not already been initialized.
    ///
    /// The value of the class or interface field is fetched and pushed onto the operand stack.
    Getstatic(u16) = 0xb2,
    /**
     * Set static field in class

     The unsigned indexbyte1 and indexbyte2 are used to construct an index into the run-time constant pool of the current class (§2.6), where the value of the index is (indexbyte1 << 8) | indexbyte2. The run-time constant pool item at that index must be a symbolic reference to a field (§5.1), which gives the name and descriptor of the field as well as a symbolic reference to the class or interface in which the field is to be found. The referenced field is resolved (§5.4.3.2).

    On successful resolution of the field, the class or interface that declared the resolved field is initialized (§5.5) if that class or interface has not already been initialized.

    The type of a value stored by a putstatic instruction must be compatible with the descriptor of the referenced field (§4.3.2). If the field descriptor type is boolean, byte, char, short, or int, then the value must be an int. If the field descriptor type is float, long, or double, then the value must be a float, long, or double, respectively. If the field descriptor type is a reference type, then the value must be of a type that is assignment compatible (JLS §5.2) with the field descriptor type. If the field is final, it must be declared in the current class, and the instruction must occur in the <clinit> method of the current class (§2.9).

    The value is popped from the operand stack and undergoes value set conversion (§2.8.3), resulting in value'. The class field is set to value
    */
    Putstatic(u16) = 0xb3,
    /// Fetch field from object
    GetField(u16) = 0xb4,
    /// Set field in object.
    ///
    ///  The unsigned indexbyte1 and indexbyte2 are used to construct an index into the run-time constant pool of the current class (§2.6), where the value of the index is (indexbyte1 << 8) | indexbyte2. The run-time constant pool item at that index must be a symbolic reference to a field (§5.1), which gives the name and descriptor of the field as well as a symbolic reference to the class in which the field is to be found. The class of objectref must not be an array. If the field is protected, and it is a member of a superclass of the current class, and the field is not declared in the same run-time package (§5.3) as the current class, then the class of objectref must be either the current class or a subclass of the current class.
    PutField(u16) = 0xb5,
    /**
     * Create new object.

    The unsigned indexbyte1 and indexbyte2 are used to construct an index into the run-time constant pool of the current class (§2.6), where the value of the index is (indexbyte1 << 8) | indexbyte2. The run-time constant pool item at the index must be a symbolic reference to a class or interface type. The named class or interface type is resolved (§5.4.3.1) and should result in a class type. Memory for a new instance of that class is allocated from the garbage-collected heap, and the instance variables of the new object are initialized to their default initial values (§2.3, §2.4). The objectref, a reference to the instance, is pushed onto the operand stack.
    */
    New(u16) = 0xbb,
    /// Create new array
    ///
    ///
    /// The count must be of type int. It is popped off the operand stack. The count represents the number of elements in the array to be created.
    ///
    /// The atype is a code that indicates the type of array to create. It must take one of the following values:
    ///
    /// | Array Type | atype |
    /// |------------|-------|
    /// | T_BOOLEAN	 | 4     |
    /// | T_CHAR     | 5     |
    /// | T_FLOAT 	 | 6     |
    /// | T_DOUBLE 	 | 7     |
    /// | T_BYTE     | 8     |
    /// | T_SHORT 	 | 9     |
    /// | T_INT 	 | 10    |
    /// | T_LONG     | 11    |
    NewArray(u8) = 0xbc,
    /// Create new array of reference
    /**
    The count must be of type int. It is popped off the operand stack. The count represents the number of components of the array to be created. The unsigned indexbyte1 and indexbyte2 are used to construct an index into the run-time constant pool of the current class (§2.6), where the value of the index is (indexbyte1 << 8) | indexbyte2. The run-time constant pool item at that index must be a symbolic reference to a class, array, or interface type. The named class, array, or interface type is resolved (§5.4.3.1). A new array with components of that type, of length count, is allocated from the garbage-collected heap, and a reference arrayref to this new array object is pushed onto the operand stack. All components of the new array are initialized to null, the default value for reference types (§2.4).
    */
    ANewArray(u16) = 0xbd,
    /// Get length of array
    ArrayLength = 0xbe,
    /// Create new multidimensional array
    ///
    /// The dimensions operand is an unsigned byte that must be greater than or equal to 1. It represents the number of dimensions of the array to be created. The operand stack must contain dimensions values. Each such value represents the number of components in a dimension of the array to be created, must be of type int, and must be non-negative. The count1 is the desired length in the first dimension, count2 in the second, etc.
    ///
    /// All of the count values are popped off the operand stack. The unsigned indexbyte1 and indexbyte2 are used to construct an index into the run-time constant pool of the current class (§2.6), where the value of the index is (indexbyte1 << 8) | indexbyte2. The run-time constant pool item at the index must be a symbolic reference to a class, array, or interface type. The named class, array, or interface type is resolved (§5.4.3.1). The resulting entry must be an array class type of dimensionality greater than or equal to dimensions.
    /// A new multidimensional array of the array type is allocated from the garbage-collected heap. If any count value is zero, no subsequent dimensions are allocated. The components of the array in the first dimension are initialized to subarrays of the type of the second dimension, and so on. The components of the last allocated dimension of the array are initialized to the default initial value (§2.3, §2.4) for the element type of the array type. A reference arrayref to the new array is pushed onto the operand stack
    MultiANewArray(u16, u8) = 0xc5,

    #[decode(wide(op = 0x15))]
    // The `wide` instruction (0xc4) modifies the behavior of another instruction so that it
    // takes a two-byte unsigned index instead of a one-byte one. These don't get a single-byte
    // discriminant of their own since 0xc4 is a prefix - see the `0xc4` match arm in `next_op`,
    // which reads the widened opcode and dispatches to the matching variant below.
    /// Load int from local variable, using a wide (u16) index.
    WideIload(u16),
    #[decode(wide(op = 0x16))]
    /// Load long from local variable, using a wide (u16) index.
    WideLload(u16),
    /// Load float from local variable, using a wide (u16) index.
    #[decode(wide(op = 0x17))]
    WideFload(u16),
    /// Load double from local variable, using a wide (u16) index.
    #[decode(wide(op = 0x18))]
    WideDload(u16),
    /// Load reference from local variable, using a wide (u16) index.
    #[decode(wide(op = 0x19))]
    WideAload(u16),
    /// Store int into local variable, using a wide (u16) index.
    #[decode(wide(op = 0x36))]
    WideIStore(u16),
    /// Store long into local variable, using a wide (u16) index.
    #[decode(wide(op = 0x37))]
    WideLStore(u16),
    /// Store float into local variable, using a wide (u16) index.
    #[decode(wide(op = 0x38))]
    WideFStore(u16),
    /// Store double into local variable, using a wide (u16) index.
    #[decode(wide(op = 0x39))]
    WideDStore(u16),
    /// Store reference into local variable, using a wide (u16) index.
    #[decode(wide(op = 0x3a))]
    WideAStore(u16),
    /// Increment local variable by constant, using a wide (u16) index and a wide (i16) constant.
    #[decode(wide(op = 0x84))]
    WideIinc(u16, i16),

    #[decode(invalid)]
    Invalid(u8),
}

impl OpCode {
    #[inline(always)]
    /// Handles some cases macro cannot
    fn custom_decode(op: u8, reader: &mut ClassByteReader, pc: &mut u16) -> Option<Self> {
        match op {
            0x10 => {
                let byte = reader.decode::<u8>().ok()? as i8;
                *pc += size_of::<u8>() as u16;
                Some(OpCode::Bipush(byte))
            }
            // TODO: too lazy for iconst<n>
            0x2 => Some(OpCode::Bipush(-1)),
            0x3..=0x8 => Some(OpCode::Bipush((op - 0x3) as i8)),
            _ => Some(OpCode::Invalid(op)),
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct Instructions<'a> {
    bytes: &'a [u8],
    pc: u16,
}

impl<'a> Instructions<'a> {
    pub const fn pc(&self) -> u16 {
        self.pc
    }

    pub const fn set_pc(&mut self, pc: u16) {
        self.pc = pc;
    }

    pub const fn raw_code(&self) -> &'a [u8] {
        self.bytes
    }

    pub fn next_op(&mut self) -> Option<OpCode> {
        if self.pc() as usize >= self.bytes.len() {
            return None;
        }

        let mut reader = ClassByteReader::new(&self.bytes[self.pc() as usize..]);
        let op = reader.read_u8().ok()?;
        self.pc += 1;

        OpCode::decode(op, &mut reader, &mut self.pc)
    }
}

impl<'a> Iterator for Instructions<'a> {
    type Item = OpCode;
    fn next(&mut self) -> Option<Self::Item> {
        self.next_op()
    }
}

#[derive(Debug, Clone)]
pub struct JVMCode {
    pub max_locals: u16,
    pub max_stack: u16,
    pub code: Box<[u8]>,
    pub exception_table: Box<[ExceptionTableEntry]>,
    pub attributes: Box<[JVMAttribute]>,
}

#[derive(Debug, Clone, Copy)]
pub struct ExceptionTableEntry {
    pub start_pc: u16,
    pub end_pc: u16,
    pub handler_pc: u16,
    pub catch_type: u16,
}

impl ClassDecode for ExceptionTableEntry {
    fn decode_from<R: ClassReader + ?Sized>(reader: &mut R) -> crate::io::Result<Self> {
        let start_pc = reader.read_u16()?;
        let end_pc = reader.read_u16()?;
        let handler_pc = reader.read_u16()?;
        let catch_type = reader.read_u16()?;

        Ok(Self {
            start_pc,
            end_pc,
            handler_pc,
            catch_type,
        })
    }
}

impl JVMCode {
    pub const fn max_locals(&self) -> u16 {
        self.max_locals
    }

    pub const fn max_stack(&self) -> u16 {
        self.max_stack
    }

    pub const fn code(&self) -> &[u8] {
        &self.code
    }

    pub const fn attributes(&self) -> &[JVMAttribute] {
        &self.attributes
    }

    pub const fn exception_table(&self) -> &[ExceptionTableEntry] {
        &self.exception_table
    }

    pub const fn instructions<'s>(&'s self) -> Instructions<'s> {
        Instructions {
            bytes: self.code(),
            pc: 0,
        }
    }
}

#[derive(Debug, Clone)]
pub enum JVMAttribute {
    Code(JVMCode),
    Unknown(Arc<str>, Box<[u8]>),
}

#[macro_export]
// Macro abuse yay!
//
// TODO: Maybe have a ConstantPool abstraction??
macro_rules! get_const {
    ($variant: ident { $($pat:tt)* }, $pool: expr, $idx:expr, $target_name: literal) => {{
        let Some(ConstantPoolEntry::$variant { $($pat)* }) = $pool.get($idx as usize) else {
            return Err($crate::invalid_data!(concat!(
                $target_name,
                " expected ",
                stringify!($variant),
                " at a valid index in the constant pool"
            )));
        };
        { ($($pat)*) }
    }};
    (UTF8 $pool: expr, $idx: expr, $target_name: literal) => {
        $crate::class::get_const!(Utf8 { string }, $pool, $idx, $target_name)
    };
}

pub use get_const;

impl JVMAttribute {
    pub fn parse(attr: AttributeInfo, constant_pool: &[ConstantPoolEntry]) -> io::Result<Self> {
        let name = get_const!(
            UTF8
            constant_pool,
            attr.attribute_name_index,
            "Attribute name"
        );

        let mut reader = ClassByteReader::new(&attr.info);
        match &**name {
            "Code" => {
                let max_stack = reader.read_u16()?;
                let max_locals = reader.read_u16()?;

                let code_length = reader.read_u32()?;
                let code = reader.decode_n(code_length as usize)?.into_boxed_slice();

                let exception_table_length = reader.read_u16()?;
                let exception_table = reader
                    .decode_n(exception_table_length as usize)?
                    .into_boxed_slice();

                let attributes_count = reader.read_u16()?;
                let mut attributes = Vec::with_capacity(attributes_count as usize);
                for _ in 0..attributes_count {
                    let raw_attr: AttributeInfo = reader.decode()?;

                    attributes.push(JVMAttribute::parse(raw_attr, constant_pool)?);
                }

                Ok(Self::Code(JVMCode {
                    max_locals,
                    max_stack,
                    code,
                    attributes: attributes.into_boxed_slice(),
                    exception_table,
                }))
            }
            _ => Ok(Self::Unknown(name.clone(), attr.info)),
        }
    }
}

#[derive(Debug)]
pub enum FieldDescriptor<'a> {
    Int,
    Long,
    Bool,
    Char,
    Byte,
    Short,
    Float,
    Double,
    Object(&'a str),
    Array,
}

impl<'a> FieldDescriptor<'a> {
    pub const fn slot_count(&self) -> usize {
        match self {
            Self::Long | Self::Double => 2,
            _ => 1,
        }
    }

    pub fn from_str(s: &'a str) -> impl Iterator<Item = Self> {
        let mut data = s.as_bytes();
        core::iter::from_fn(move || {
            if data.is_empty() {
                return None;
            }

            let (desc, rest) = data.split_at(1);
            data = rest;

            let kind = match desc[0] {
                b'I' => Self::Int,
                b'J' => Self::Long,
                b'D' => Self::Double,
                b'F' => Self::Float,
                b'S' => Self::Short,
                b'C' => Self::Char,
                b'B' => Self::Byte,
                b'Z' => Self::Bool,
                b'L' => {
                    let semi = data.iter().position(|&b| b == b';')?;

                    let (classname, rest) = data.split_at(semi);
                    data = &rest[1..];

                    Self::Object(unsafe { core::str::from_utf8_unchecked(classname) })
                }
                b'[' => Self::Array,
                _ => return None,
            };
            Some(kind)
        })
    }
}

#[derive(Debug)]
pub struct MethodDescriptor<'a> {
    args: &'a [u8],
    ret: &'a [u8],
}

impl<'a> MethodDescriptor<'a> {
    pub fn new(desc: &'a str) -> Self {
        let mut split = desc.as_bytes().split(|c| [b'(', b')'].contains(c));

        Self {
            args: split.nth(1).unwrap_or_default(),
            ret: split.next().unwrap_or_default(),
        }
    }

    pub fn ret(&self) -> &'a [u8] {
        self.ret
    }

    pub fn args_descriptors(
        &self,
    ) -> impl Iterator<Item = impl Iterator<Item = FieldDescriptor<'a>>> {
        self.args()
            .map(|a| FieldDescriptor::from_str(unsafe { core::str::from_utf8_unchecked(a) }))
    }

    pub fn args(&self) -> impl Iterator<Item = &'a [u8]> {
        let mut data = self.args;

        core::iter::from_fn(move || {
            if data.is_empty() {
                return None;
            }

            let mut i = 0;
            while data.get(i) == Some(&b'[') {
                i += 1;
            }

            let end = match data.get(i)? {
                b'L' => {
                    let semi = data[i..].iter().position(|&b| b == b';')?;
                    i + semi + 1
                }
                _ => i + 1,
            };

            let (item, rest) = data.split_at(end);
            data = rest;
            Some(item)
        })
    }

    pub fn args_size(&self) -> usize {
        self.args_descriptors()
            .map(|mut descs| descs.next().map(|n| n.slot_count()).unwrap_or_default())
            .sum()
    }
}

#[derive(Debug, Clone)]
pub struct JVMField {
    name: Arc<str>,
    descriptor: Arc<str>,
    slot_count: usize,
    access_flags: JVMAccessFlag,
    attributes: Box<[JVMAttribute]>,
}

impl JVMField {
    pub fn name(&self) -> &str {
        &*self.name
    }

    pub fn raw_descriptor(&self) -> &str {
        &*self.descriptor
    }

    pub fn descriptors<'s>(&'s self) -> impl Iterator<Item = FieldDescriptor<'s>> {
        FieldDescriptor::from_str(&self.descriptor)
    }

    pub fn slot_count(&self) -> usize {
        self.slot_count
    }

    pub const fn access_flags(&self) -> JVMAccessFlag {
        self.access_flags
    }

    pub const fn attributes(&self) -> &[JVMAttribute] {
        &self.attributes
    }

    pub fn parse(info: FieldInfo, constant_pool: &[ConstantPoolEntry]) -> io::Result<Self> {
        let name = get_const!(
            UTF8
            constant_pool,
            info.name_index,
            "Field name"
        );
        let descriptor = get_const!(
            UTF8
            constant_pool,
            info.descriptor_index,
            "Field descriptor"
        );

        let mut attributes = Vec::with_capacity(info.attributes.len().saturating_sub(1));

        let access_flags = JVMAccessFlag::from_bits_retain(info.access_flags);
        for attr in info.attributes {
            let parsed = JVMAttribute::parse(attr, constant_pool)?;
            attributes.push(parsed);
        }

        let slot_count = FieldDescriptor::from_str(descriptor)
            .next()
            .map(|d| d.slot_count())
            .unwrap_or_default();
        Ok(Self {
            access_flags,
            name: name.clone(),
            descriptor: descriptor.clone(),
            slot_count,
            attributes: attributes.into_boxed_slice(),
        })
    }
}

#[derive(Debug, Clone)]
pub struct JVMMethod {
    pub name: Arc<str>,
    pub descriptor: Arc<str>,
    pub args_size: usize,
    pub access_flags: JVMAccessFlag,
    pub code: Option<JVMCode>,
    pub attributes: Box<[JVMAttribute]>,
}

impl JVMMethod {
    pub fn name(&self) -> &str {
        &*self.name
    }

    pub fn raw_descriptor(&self) -> &str {
        &*self.descriptor
    }

    pub fn descriptor<'s>(&'s self) -> MethodDescriptor<'s> {
        MethodDescriptor::new(&self.descriptor)
    }

    pub fn args_size(&self) -> usize {
        self.args_size
    }

    pub const fn access_flags(&self) -> JVMAccessFlag {
        self.access_flags
    }

    pub const fn code(&self) -> Option<&JVMCode> {
        self.code.as_ref()
    }

    pub const fn attributes(&self) -> &[JVMAttribute] {
        &self.attributes
    }

    pub fn parse(info: MethodInfo, constant_pool: &[ConstantPoolEntry]) -> io::Result<Self> {
        let name = get_const!(
            UTF8
            constant_pool,
            info.name_index,
            "Method name"
        );
        let descriptor = get_const!(
            UTF8
            constant_pool,
            info.descriptor_index,
            "Method descriptor"
        );

        let mut code = None;
        let mut attributes = Vec::with_capacity(info.attributes.len().saturating_sub(1));

        let access_flags = JVMAccessFlag::from_bits_retain(info.access_flags);
        for attr in info.attributes {
            let parsed = JVMAttribute::parse(attr, constant_pool)?;

            if let JVMAttribute::Code(attr_code) = parsed {
                if access_flags.contains(JVMAccessFlag::ACC_ABSTRACT)
                    || access_flags.contains(JVMAccessFlag::ACC_NATIVE)
                {
                    return Err(invalid_data!(
                        "Native and abstract methods must not have code"
                    ));
                }
                if code.is_some() {
                    return Err(invalid_data!("More the one code attribute in method"));
                }
                code = Some(attr_code);
            } else {
                attributes.push(parsed);
            }
        }

        let args_size = MethodDescriptor::new(descriptor).args_size();
        Ok(Self {
            access_flags,
            name: name.clone(),
            descriptor: descriptor.clone(),
            args_size,
            code,
            attributes: attributes.into_boxed_slice(),
        })
    }
}

/// The difference between this and [`RawClassFile`] is that this is more resolved.
/// however unlike [`JVMMethod`], and [`JVMAttribute`], this is not fully resolved for example the constant pool is still raw.
///
/// FIXME: bad design, it is necessary for this to go into another layer of conversion for it to be usable with the VM, this lib must provide everything it can for parsing while being no_std but how far should it go?
#[derive(Debug, Clone)]
pub struct Class {
    pub this_name: Arc<str>,
    pub super_name: Arc<str>,
    pub minor_version: u16,
    pub major_version: u16,
    pub access_flags: JVMAccessFlag,
    pub constant_pool: Box<[ConstantPoolEntry]>,
    pub methods: Box<[JVMMethod]>,
    pub fields: Box<[JVMField]>,
    pub attributes: Box<[JVMAttribute]>,
}

impl Class {
    /// Decodes and parses a class from a given reader.
    pub fn decode(reader: &mut impl ClassReader) -> io::Result<Self> {
        let raw_class: RawClassFile = reader.decode()?;
        Self::parse(raw_class)
    }

    /// Version as (major, minor)
    pub const fn version(&self) -> (u16, u16) {
        (self.major_version, self.minor_version)
    }

    pub fn name(&self) -> &Arc<str> {
        &self.this_name
    }

    pub fn super_name(&self) -> &Arc<str> {
        &self.super_name
    }

    pub const fn access_flags(&self) -> JVMAccessFlag {
        self.access_flags
    }

    pub const fn methods(&self) -> &[JVMMethod] {
        &self.methods
    }

    pub const fn constant_pool(&self) -> &[ConstantPoolEntry] {
        &self.constant_pool
    }

    pub const fn attributes(&self) -> &[JVMAttribute] {
        &self.attributes
    }

    pub fn parse(raw: RawClassFile) -> io::Result<Self> {
        let constant_pool = raw.constant_pool;

        let this_index = raw.this_class;
        let super_index = raw.super_class;

        let this_class = get_const!(
            Class { name_index },
            constant_pool,
            this_index,
            "this_class"
        );
        let super_class = get_const!(
            Class { name_index },
            constant_pool,
            super_index,
            "super_class"
        );

        let this_name = get_const!(UTF8 constant_pool, *this_class, "this_class name").clone();
        let super_name = get_const!(UTF8 constant_pool, *super_class, "super_class name").clone();

        let mut attributes = Vec::with_capacity(raw.attributes.len());
        for attr in raw.attributes {
            attributes.push(JVMAttribute::parse(attr, &constant_pool)?);
        }

        let mut methods = Vec::with_capacity(raw.methods.len());
        for meth in raw.methods {
            methods.push(JVMMethod::parse(meth, &constant_pool)?);
        }

        let mut fields = Vec::with_capacity(raw.fields.len());
        for field in raw.fields {
            fields.push(JVMField::parse(field, &constant_pool)?);
        }

        Ok(Self {
            fields: fields.into_boxed_slice(),
            this_name,
            super_name,
            minor_version: raw.minor_version,
            major_version: raw.major_version,
            access_flags: JVMAccessFlag::from_bits_retain(raw.access_flags),
            constant_pool,
            methods: methods.into_boxed_slice(),
            attributes: attributes.into_boxed_slice(),
        })
    }
}
