mod constant_pool;
mod raw;

use crate::io;
use crate::io::invalid_data;

pub use constant_pool::*;
pub use raw::*;

extern crate alloc;
use alloc::boxed::Box;
use alloc::sync::Arc;

use crate::io::{ClassByteReader, ClassDecode, ClassReader};

bitflags::bitflags! {
    /**
     The value of the access_flags item is a mask of flags used to denote access permissions to and properties of this class or interface. The interpretation of each flag, when set, is specified in Table 4.1-A.
     Table 4.1-A. Class access and property modifiers
   */
    #[derive(Debug, Clone, Copy)]
    pub struct JVMAccessFlag: u16 {
        /// Declared public; may be accessed from outside its package.
         const ACC_PUBLIC = 0x0001;
        /// Declared private; accessible only within the defining class.
         const ACC_PRIVATE = 0x0002;
        /// Declared protected; may be accessed within subclasses.
         const ACC_PROTECTED = 0x0004;
        /// Declared static.
         const ACC_STATIC = 0x0008;
        /// Declared final; must not be overridden (§5.4.5).
         const ACC_FINAL = 0x0010;
        /// Declared synchronized; invocation is wrapped by a monitor use.
         const ACC_SYNCHRONIZED = 0x0020;
        /// A bridge method, generated by the compiler.
         const ACC_BRIDGE = 0x0040;
        /// Declared with variable number of arguments.
         const ACC_VARARGS = 0x0080;
        /// Declared native; implemented in a language other than Java.
         const ACC_NATIVE = 0x0100;
        /// Declared abstract; no implementation is provided.
         const ACC_ABSTRACT = 0x0400;
        /// Declared strictfp; floating-point mode is FP-strict.
         const ACC_STRICT = 0x0800;
        /// Declared synthetic; not present in the source code.
         const ACC_SYNTHETIC = 0x1000;
    }
}

/// Describes all (implemented) JVM instructions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum OpCode {
    /// Load int from local variable
    ///
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6). The local variable at index must contain an int. The value of the local variable at index is pushed onto the operand stack.
    Iload(u8) = 0x15,
    /// Store int into local variable
    ///
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6). The value on the top of the operand stack must be of type int. It is popped from the operand stack, and the value of the local variable at index is set to value.
    IStore(u8) = 0x36,
    /// Push Byte. The immediate byte is sign-extended to an int value. That value is pushed onto the operand stack.
    Bipush(i8) = 0x10,
    /// Increment local variable by constant.
    /// The index is an unsigned byte that must be an index into the local variable array of the current frame (§2.6).
    ///
    /// The const is an immediate signed byte. The local variable at index must contain an int. The value const is first sign-extended to an int, and then the local variable at index is incremented by that amount.
    Iinc(u8, i8) = 0x84,
    /// Multiply int.
    ///
    ///  Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 * value2. The result is pushed onto the operand stack.
    ///
    /// The result is the 32 low-order bits of the true mathematical result in a sufficiently wide two's-complement format, represented as a value of type int. If overflow occurs, then the sign of the result may not be the same as the sign of the mathematical multiplication of the two values.
    ///
    /// Despite the fact that overflow may occur, execution of an imul instruction never throws a run-time exception
    Imul = 0x68,
    /// Divide int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 / value2. The result is pushed onto the operand stack.
    Idiv = 0x6c,
    /// Subtract int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 - value2. The result is pushed onto the operand stack.
    Isub = 0x64,
    /// Add int.
    ///
    /// Both value1 and value2 must be of type int. The values are popped from the operand stack. The int result is value1 + value2. The result is pushed onto the operand stack.
    Iadd = 0x60,
    /// Negate int.
    ///
    /// The value must be of type int. It is popped from the operand stack. The int result is -value. The result is pushed onto the operand stack.
    Ineg = 0x74,
    /// Branch always/
    Goto(i16) = 0xa7,
    /// Branch if int comparison succeeds.
    ///
    /// Both value1 and value2 must be of type int. They are both popped from the operand stack and compared. All comparisons are signed. The results of the comparison are as follows:
    ///
    /// if_icmpeq succeeds if and only if value1 = value2
    IfIcmpEq(i16) = 0x9f,
    /// Branch if int comparison fails.
    ///
    /// Both value1 and value2 must be of type int. They are both popped from the operand stack and compared. All comparisons are signed. The results of the comparison are as follows:
    ///
    /// if_icmpne succeeds if and only if value1 != value2
    IfIcmpNe(i16) = 0xa0,
    /// Branch if int comparison with zero succeeds.
    /// The value must be of type int. It is popped from the operand stack and compared against zero. All comparisons are signed. The results of the comparisons are as follows:
    /// - ifne succeeds if and only if value ≠ 0.
    IfNe(i16) = 0x9a,
    /// Branch if int comparison with zero fails.
    /// The value must be of type int. It is popped from the operand stack and compared against zero. All comparisons are signed. The results of the comparisons are as follows:
    /// - ifeq succeeds if and only if value = 0.
    IfEq(i16) = 0x99,
    /// Return int from method.
    ///
    ///  The current method must have return type boolean, byte, short, char, or int. The value must be of type int. If the current method is a synchronized method, the monitor entered or reentered on invocation of the method is updated and possibly exited as if by execution of a monitorexit instruction (§monitorexit) in the current thread. If no exception is thrown, value is popped from the operand stack of the current frame (§2.6) and pushed onto the operand stack of the frame of the invoker. Any other values on the operand stack of the current method are discarded.
    IReturn = 0xac,
    InvokeStatic(u16) = 0xb8,
    /// Return void from method.
    Return = 0xb1,
    /// Get static field from class.
    /// The unsigned indexbyte1 and indexbyte2 are used to construct an index into the run-time constant pool of the current class (§2.6), where the value of the index is (indexbyte1 << 8) | indexbyte2. The run-time constant pool item at that index must be a symbolic reference to a field (§5.1), which gives the name and descriptor of the field as well as a symbolic reference to the class or interface in which the field is to be found. The referenced field is resolved (§5.4.3.2).
    ///
    /// On successful resolution of the field, the class or interface that declared the resolved field is initialized (§5.5) if that class or interface has not already been initialized.
    ///
    /// The value of the class or interface field is fetched and pushed onto the operand stack.
    Getstatic(u16) = 0xb2,
    /**
     * Set static field in class

     The unsigned indexbyte1 and indexbyte2 are used to construct an index into the run-time constant pool of the current class (§2.6), where the value of the index is (indexbyte1 << 8) | indexbyte2. The run-time constant pool item at that index must be a symbolic reference to a field (§5.1), which gives the name and descriptor of the field as well as a symbolic reference to the class or interface in which the field is to be found. The referenced field is resolved (§5.4.3.2).

    On successful resolution of the field, the class or interface that declared the resolved field is initialized (§5.5) if that class or interface has not already been initialized.

    The type of a value stored by a putstatic instruction must be compatible with the descriptor of the referenced field (§4.3.2). If the field descriptor type is boolean, byte, char, short, or int, then the value must be an int. If the field descriptor type is float, long, or double, then the value must be a float, long, or double, respectively. If the field descriptor type is a reference type, then the value must be of a type that is assignment compatible (JLS §5.2) with the field descriptor type. If the field is final, it must be declared in the current class, and the instruction must occur in the <clinit> method of the current class (§2.9).

    The value is popped from the operand stack and undergoes value set conversion (§2.8.3), resulting in value'. The class field is set to value
    */
    Putstatic(u16) = 0xb3,
    Invalid(u8),
}

#[derive(Debug, Clone, Copy)]
pub struct Instructions<'a> {
    bytes: &'a [u8],
    pc: u16,
}

impl<'a> Instructions<'a> {
    pub const fn pc(&self) -> u16 {
        self.pc
    }

    pub const fn set_pc(&mut self, pc: u16) {
        self.pc = pc;
    }

    pub const fn raw_code(&self) -> &'a [u8] {
        self.bytes
    }

    pub fn next_op(&mut self) -> Option<OpCode> {
        if self.pc() as usize >= self.bytes.len() {
            return None;
        }

        let mut reader = ClassByteReader::new(&self.bytes[self.pc() as usize..]);
        let op = reader.read_u8().ok()?;
        self.pc += 1;

        macro_rules! opnd {
            ($t: ty) => {{
                let Ok(opr): Result<$t, _> = reader.decode() else {
                    return Some(OpCode::Invalid(op));
                };

                self.pc += size_of::<$t>() as u16;
                opr
            }};
        }

        match op {
            0x10 => {
                let byte = opnd!(u8) as i8;
                Some(OpCode::Bipush(byte))
            }
            // TODO: Too lazy for iconst<n>
            0x2 => Some(OpCode::Bipush(-1)),
            0x3..=0x8 => Some(OpCode::Bipush((op - 0x3) as i8)),
            0x15 => {
                let idx = opnd!(u8);
                Some(OpCode::Iload(idx))
            }
            0x1a | 0x1b | 0x1c | 0x1d => {
                // TODO: too lazy to do iload<n>
                let idx = op - 0x1a;
                Some(OpCode::Iload(idx))
            }
            0x36 => {
                let idx = opnd!(u8);
                Some(OpCode::IStore(idx))
            }
            0x3b | 0x3c | 0x3d | 0x3e => {
                let idx = op - 0x3b;
                // TODO: too lazy to do istore<n>
                Some(OpCode::IStore(idx))
            }
            0x84 => Some(OpCode::Iinc(opnd!(u8), opnd!(u8) as i8)),
            0x68 => Some(OpCode::Imul),
            0x6c => Some(OpCode::Idiv),
            0x74 => Some(OpCode::Ineg),
            0x64 => Some(OpCode::Isub),
            0x60 => Some(OpCode::Iadd),
            0x9f => {
                let pc = opnd!(u16) as i16;
                Some(OpCode::IfIcmpEq(pc))
            }
            0xa0 => {
                let pc = opnd!(u16) as i16;
                Some(OpCode::IfIcmpNe(pc))
            }
            0x99 => {
                let pc = opnd!(u16) as i16;
                Some(OpCode::IfEq(pc))
            }
            0x9a => {
                let pc = opnd!(u16) as i16;
                Some(OpCode::IfNe(pc))
            }
            0xa7 => {
                let pc = opnd!(u16) as i16;
                Some(OpCode::Goto(pc))
            }
            0xac => Some(OpCode::IReturn),
            0xb8 => Some(OpCode::InvokeStatic(opnd!(u16))),
            0xb1 => Some(OpCode::Return),
            0xb3 => Some(OpCode::Putstatic(opnd!(u16))),
            0xb2 => Some(OpCode::Getstatic(opnd!(u16))),
            _ => Some(OpCode::Invalid(op)),
        }
    }
}

impl<'a> Iterator for Instructions<'a> {
    type Item = OpCode;
    fn next(&mut self) -> Option<Self::Item> {
        self.next_op()
    }
}

#[derive(Debug, Clone)]
pub struct JVMCode {
    max_locals: u16,
    max_stack: u16,
    code: Box<[u8]>,
    exception_table: Box<[ExceptionTableEntry]>,
    attributes: Box<[JVMAttribute]>,
}

#[derive(Debug, Clone, Copy)]
pub struct ExceptionTableEntry {
    pub start_pc: u16,
    pub end_pc: u16,
    pub handler_pc: u16,
    pub catch_type: u16,
}

impl ClassDecode for ExceptionTableEntry {
    fn decode_from<R: ClassReader + ?Sized>(reader: &mut R) -> crate::io::Result<Self> {
        let start_pc = reader.read_u16()?;
        let end_pc = reader.read_u16()?;
        let handler_pc = reader.read_u16()?;
        let catch_type = reader.read_u16()?;

        Ok(Self {
            start_pc,
            end_pc,
            handler_pc,
            catch_type,
        })
    }
}

impl JVMCode {
    pub const fn max_locals(&self) -> u16 {
        self.max_locals
    }

    pub const fn max_stack(&self) -> u16 {
        self.max_stack
    }

    pub const fn code(&self) -> &[u8] {
        &self.code
    }

    pub const fn attributes(&self) -> &[JVMAttribute] {
        &self.attributes
    }

    pub const fn exception_table(&self) -> &[ExceptionTableEntry] {
        &self.exception_table
    }

    pub const fn instructions<'s>(&'s self) -> Instructions<'s> {
        Instructions {
            bytes: self.code(),
            pc: 0,
        }
    }
}

#[derive(Debug, Clone)]
pub enum JVMAttribute {
    Code(JVMCode),
    Unknown(Arc<str>, Box<[u8]>),
}

#[macro_export]
// Macro abuse yay!
//
// TODO: Maybe have a ConstantPool abstraction??
macro_rules! get_const {
    ($variant: ident { $($pat:tt)* }, $pool: expr, $idx:expr, $target_name: literal) => {{
        let Some(ConstantPoolEntry::$variant { $($pat)* }) = $pool.get($idx as usize) else {
            return Err($crate::invalid_data!(concat!(
                $target_name,
                " expected ",
                stringify!($variant),
                " at a valid index in the constant pool"
            )));
        };
        { ($($pat)*) }
    }};
    (UTF8 $pool: expr, $idx: expr, $target_name: literal) => {
        $crate::class::get_const!(Utf8 { string }, $pool, $idx, $target_name)
    };
}

pub use get_const;

impl JVMAttribute {
    pub fn parse(attr: AttributeInfo, constant_pool: &[ConstantPoolEntry]) -> io::Result<Self> {
        let name = get_const!(
            UTF8
            constant_pool,
            attr.attribute_name_index,
            "Attribute name"
        );

        let mut reader = ClassByteReader::new(&attr.info);
        match &**name {
            "Code" => {
                let max_stack = reader.read_u16()?;
                let max_locals = reader.read_u16()?;

                let code_length = reader.read_u32()?;
                let code = reader.decode_n(code_length as usize)?.into_boxed_slice();

                let exception_table_length = reader.read_u16()?;
                let exception_table = reader
                    .decode_n(exception_table_length as usize)?
                    .into_boxed_slice();

                let attributes_count = reader.read_u16()?;
                let mut attributes = Vec::with_capacity(attributes_count as usize);
                for _ in 0..attributes_count {
                    let raw_attr: AttributeInfo = reader.decode()?;

                    attributes.push(JVMAttribute::parse(raw_attr, constant_pool)?);
                }

                Ok(Self::Code(JVMCode {
                    max_locals,
                    max_stack,
                    code,
                    attributes: attributes.into_boxed_slice(),
                    exception_table,
                }))
            }
            _ => Ok(Self::Unknown(name.clone(), attr.info)),
        }
    }
}

#[derive(Debug)]
pub enum FieldDescriptor<'a> {
    Int,
    Long,
    Bool,
    Char,
    Byte,
    Short,
    Float,
    Double,
    Object(&'a str),
    Array,
}

impl<'a> FieldDescriptor<'a> {
    pub const fn slot_count(&self) -> usize {
        match self {
            Self::Long | Self::Double => 2,
            _ => 1,
        }
    }

    pub fn from_str(s: &'a str) -> impl Iterator<Item = Self> {
        let mut data = s.as_bytes();
        core::iter::from_fn(move || {
            if data.is_empty() {
                return None;
            }

            let (desc, rest) = data.split_at(1);
            data = rest;

            let kind = match desc[0] {
                b'I' => Self::Int,
                b'J' => Self::Long,
                b'D' => Self::Double,
                b'F' => Self::Float,
                b'S' => Self::Short,
                b'C' => Self::Char,
                b'B' => Self::Byte,
                b'Z' => Self::Bool,
                b'L' => {
                    let semi = data.iter().position(|&b| b == b';')?;

                    let (classname, rest) = data.split_at(semi);
                    data = &rest[1..];

                    Self::Object(unsafe { core::str::from_utf8_unchecked(classname) })
                }
                b'[' => Self::Array,
                _ => return None,
            };
            Some(kind)
        })
    }
}

#[derive(Debug)]
pub struct MethodDescriptor<'a> {
    args: &'a [u8],
    ret: &'a [u8],
}

impl<'a> MethodDescriptor<'a> {
    pub fn new(desc: &'a str) -> Self {
        let mut split = desc.as_bytes().split(|c| [b'(', b')'].contains(c));

        Self {
            args: split.nth(1).unwrap_or_default(),
            ret: split.next().unwrap_or_default(),
        }
    }

    pub fn ret(&self) -> &'a [u8] {
        self.ret
    }

    pub fn args_descriptors(
        &self,
    ) -> impl Iterator<Item = impl Iterator<Item = FieldDescriptor<'a>>> {
        self.args()
            .map(|a| FieldDescriptor::from_str(unsafe { core::str::from_utf8_unchecked(a) }))
    }

    pub fn args(&self) -> impl Iterator<Item = &'a [u8]> {
        let mut data = self.args;

        core::iter::from_fn(move || {
            if data.is_empty() {
                return None;
            }

            let mut i = 0;
            while data.get(i) == Some(&b'[') {
                i += 1;
            }

            let end = match data.get(i)? {
                b'L' => {
                    let semi = data[i..].iter().position(|&b| b == b';')?;
                    i + semi + 1
                }
                _ => i + 1,
            };

            let (item, rest) = data.split_at(end);
            data = rest;
            Some(item)
        })
    }

    pub fn args_size(&self) -> usize {
        self.args_descriptors()
            .map(|mut descs| descs.next().map(|n| n.slot_count()).unwrap_or_default())
            .sum()
    }
}

#[derive(Debug, Clone)]
pub struct JVMField {
    name: Arc<str>,
    descriptor: Arc<str>,
    slot_count: usize,
    access_flags: JVMAccessFlag,
    attributes: Box<[JVMAttribute]>,
}

impl JVMField {
    pub fn name(&self) -> &str {
        &*self.name
    }

    pub fn raw_descriptor(&self) -> &str {
        &*self.descriptor
    }

    pub fn descriptors<'s>(&'s self) -> impl Iterator<Item = FieldDescriptor<'s>> {
        FieldDescriptor::from_str(&self.descriptor)
    }

    pub fn slot_count(&self) -> usize {
        self.slot_count
    }

    pub const fn access_flags(&self) -> JVMAccessFlag {
        self.access_flags
    }

    pub const fn attributes(&self) -> &[JVMAttribute] {
        &self.attributes
    }

    pub fn parse(info: FieldInfo, constant_pool: &[ConstantPoolEntry]) -> io::Result<Self> {
        let name = get_const!(
            UTF8
            constant_pool,
            info.name_index,
            "Field name"
        );
        let descriptor = get_const!(
            UTF8
            constant_pool,
            info.descriptor_index,
            "Field descriptor"
        );

        let mut attributes = Vec::with_capacity(info.attributes.len().saturating_sub(1));

        let access_flags = JVMAccessFlag::from_bits_retain(info.access_flags);
        for attr in info.attributes {
            let parsed = JVMAttribute::parse(attr, constant_pool)?;
            attributes.push(parsed);
        }

        let slot_count = FieldDescriptor::from_str(descriptor)
            .next()
            .map(|d| d.slot_count())
            .unwrap_or_default();
        Ok(Self {
            access_flags,
            name: name.clone(),
            descriptor: descriptor.clone(),
            slot_count,
            attributes: attributes.into_boxed_slice(),
        })
    }
}

#[derive(Debug, Clone)]
pub struct JVMMethod {
    name: Arc<str>,
    descriptor: Arc<str>,
    args_size: usize,
    access_flags: JVMAccessFlag,
    code: Option<JVMCode>,
    attributes: Box<[JVMAttribute]>,
}

impl JVMMethod {
    pub fn name(&self) -> &str {
        &*self.name
    }

    pub fn raw_descriptor(&self) -> &str {
        &*self.descriptor
    }

    pub fn descriptor<'s>(&'s self) -> MethodDescriptor<'s> {
        MethodDescriptor::new(&self.descriptor)
    }

    pub fn args_size(&self) -> usize {
        self.args_size
    }

    pub const fn access_flags(&self) -> JVMAccessFlag {
        self.access_flags
    }

    pub const fn code(&self) -> Option<&JVMCode> {
        self.code.as_ref()
    }

    pub const fn attributes(&self) -> &[JVMAttribute] {
        &self.attributes
    }

    pub fn parse(info: MethodInfo, constant_pool: &[ConstantPoolEntry]) -> io::Result<Self> {
        let name = get_const!(
            UTF8
            constant_pool,
            info.name_index,
            "Method name"
        );
        let descriptor = get_const!(
            UTF8
            constant_pool,
            info.descriptor_index,
            "Method descriptor"
        );

        let mut code = None;
        let mut attributes = Vec::with_capacity(info.attributes.len().saturating_sub(1));

        let access_flags = JVMAccessFlag::from_bits_retain(info.access_flags);
        for attr in info.attributes {
            let parsed = JVMAttribute::parse(attr, constant_pool)?;

            if let JVMAttribute::Code(attr_code) = parsed {
                if access_flags.contains(JVMAccessFlag::ACC_ABSTRACT)
                    || access_flags.contains(JVMAccessFlag::ACC_NATIVE)
                {
                    return Err(invalid_data!(
                        "Native and abstract methods must not have code"
                    ));
                }
                if code.is_some() {
                    return Err(invalid_data!("More the one code attribute in method"));
                }
                code = Some(attr_code);
            } else {
                attributes.push(parsed);
            }
        }

        let args_size = MethodDescriptor::new(descriptor).args_size();
        Ok(Self {
            access_flags,
            name: name.clone(),
            descriptor: descriptor.clone(),
            args_size,
            code,
            attributes: attributes.into_boxed_slice(),
        })
    }
}

/// The difference between this and [`RawClassFile`] is that this is more resolved.
/// however unlike [`JVMMethod`], and [`JVMAttribute`], this is not fully resolved for example the constant pool is still raw.
///
/// FIXME: bad design, it is necessary for this to go into another layer of conversion for it to be usable with the VM, this lib must provide everything it can for parsing while being no_std but how far should it go?
#[derive(Debug, Clone)]
pub struct Class {
    pub this_name: Arc<str>,
    pub super_name: Arc<str>,
    pub minor_version: u16,
    pub major_version: u16,
    pub access_flags: JVMAccessFlag,
    pub constant_pool: Box<[ConstantPoolEntry]>,
    pub methods: Box<[JVMMethod]>,
    pub fields: Box<[JVMField]>,
    pub attributes: Box<[JVMAttribute]>,
}

impl Class {
    /// Decodes and parses a class from a given reader.
    pub fn decode(reader: &mut impl ClassReader) -> io::Result<Self> {
        let raw_class: RawClassFile = reader.decode()?;
        Self::parse(raw_class)
    }

    /// Version as (major, minor)
    pub const fn version(&self) -> (u16, u16) {
        (self.major_version, self.minor_version)
    }

    pub fn name(&self) -> &Arc<str> {
        &self.this_name
    }

    pub fn super_name(&self) -> &Arc<str> {
        &self.super_name
    }

    pub const fn access_flags(&self) -> JVMAccessFlag {
        self.access_flags
    }

    pub const fn methods(&self) -> &[JVMMethod] {
        &self.methods
    }

    pub const fn constant_pool(&self) -> &[ConstantPoolEntry] {
        &self.constant_pool
    }

    pub const fn attributes(&self) -> &[JVMAttribute] {
        &self.attributes
    }

    pub fn parse(raw: RawClassFile) -> io::Result<Self> {
        let constant_pool = raw.constant_pool;

        let this_index = raw.this_class;
        let super_index = raw.super_class;

        let this_class = get_const!(
            Class { name_index },
            constant_pool,
            this_index,
            "this_class"
        );
        let super_class = get_const!(
            Class { name_index },
            constant_pool,
            super_index,
            "super_class"
        );

        let this_name = get_const!(UTF8 constant_pool, *this_class, "this_class name").clone();
        let super_name = get_const!(UTF8 constant_pool, *super_class, "super_class name").clone();

        let mut attributes = Vec::with_capacity(raw.attributes.len());
        for attr in raw.attributes {
            attributes.push(JVMAttribute::parse(attr, &constant_pool)?);
        }

        let mut methods = Vec::with_capacity(raw.methods.len());
        for meth in raw.methods {
            methods.push(JVMMethod::parse(meth, &constant_pool)?);
        }

        let mut fields = Vec::with_capacity(raw.fields.len());
        for field in raw.fields {
            fields.push(JVMField::parse(field, &constant_pool)?);
        }

        Ok(Self {
            fields: fields.into_boxed_slice(),
            this_name,
            super_name,
            minor_version: raw.minor_version,
            major_version: raw.major_version,
            access_flags: JVMAccessFlag::from_bits_retain(raw.access_flags),
            constant_pool,
            methods: methods.into_boxed_slice(),
            attributes: attributes.into_boxed_slice(),
        })
    }
}
